### Create new user
POST http://localhost:5000/v1/auth/
Content-Type: application/json

{
"name":"sefat",
"email":"sefat1@amazon.com", 
"password":"Password5%",
"confirmPassword":"Password5%",
"phone":"46853215"
}



###Login
POST http://localhost:5000/v1/auth/login
Content-Type: application/json

{
"name":"sefat",
"email":"sefat1@amazon.com", 
"password":"Password5%",
"confirmPassword":"Password5%",
"phone":"46853215"
}



### Create new Product
POST http://localhost:5000/v1/auth/
Content-Type: application/json

{ 
        "url": "https://rukminim1.flixcart.com/image/150/150/kapoo7k0/electric-kettle/p/6/s/pigeon-favourite-original-imafs7xhj5uwgrh4.jpeg?q=70", 
        "detailUrl": "https://rukminim1.flixcart.com/image/416/416/kapoo7k0/electric-kettle/p/6/s/pigeon-favourite-original-imafs7xhj5uwgrh4.jpeg?q=70",
        "title": {
            "shortTitle": "Home & Kitchen",
            "longTitle": "Pigeon FAVOURITE Electric Kettle  (1.5 L, Silver, Black)"
        }, 
        "price": {
            "mrp": 395,
            "cost": 225,
            "discount": "47%"
        },
        "description": "This electric kettle from Pigeon will soon become a travelers best friend, a hostelite saviour and an answer to all the midnight cravings. With this handy appliance, you can boil water and use it to make instant noodles, packet soup, coffee and green tea.",
        "discount": "Extra 10% Off", 
        "tagline": "Deal of the day" 
    }



### Get all Products
GET http://localhost:5000/v1/products/
Content-Type: application/json



### Get a specific Product
GET http://localhost:5000/v1/products/63592f3aa29b93357b2956ef
Content-Type: application/json